# #
# Workers
#
# Define config of crazy workers
#
# YAML version 1.2
#
# @package    kzarshenas/crazyphp
# @author     kekefreedog <kevin.zarshenas@gmail.com>
# @copyright  2022-2024 Kévin Zarshenas
# #
Workers:
  list: null
  log:
    path: "@app_root/logs/workers"
  processes: auto