# #
# Database
#
# Define default config of database of the Crazy App
#
# YAML version 1.2
#
# @package    kzarshenas/crazyphp
# @author     kekefreedog <kevin.zarshenas@gmail.com>
# @copyright  2022-2022 Kévin Zarshenas
# #
Database:
  mongodb:
    engine: mangodb
    port: null
    root:
      login: root
      password: password
