# #
# Database
#
# Define default config of database of the Crazy App
#
# YAML version 1.2
#
# @package    kzarshenas/crazyphp
# @author     kekefreedog <kevin.zarshenas@gmail.com>
# @copyright  2022-2022 Kévin Zarshenas
# #
Database:
  mangodb:
    engine: mangodb
    name: '{{app.name}}'
    prefix: kevinzar_
    host: localhost
    port: 5432
    root:
      login: admin
      password: admin
    users:
      - name: null
        login: null
        password: null
