FROM phpdockerio/php:8.1-fpm
WORKDIR ${PWD}
RUN apt-get update; \
    apt-get -y --no-install-recommends install \
        git \ 
{{#if _config.Database.collection.mongodb}}        php8.1-mongodb; \
{{/if}}    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*