FROM phpdockerio/php:8.1-fpm
# WORKDIR "/Users/kzarshenas/Sites/CrazyTest"
WORKDIR "{{app.root}}"

RUN apt-get update; \
    apt-get -y --no-install-recommends install \
        git \ 
        php8.1-mongodb; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
