name: CI
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v5
    - uses: php-actions/phpunit@v3
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        configuration: tests/phpunit.xml
        memory_limit: 256M
