# Action
name: CI
# Hook
on: [push]
# Jobs
jobs:
  # PHP Unit
  phpunit:
    # OS
    runs-on: ubuntu-latest
    # Steps
    steps:
    # Checkout
    - uses: actions/checkout@v2      
    # PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, redis
          tools: composer:v2
          coverage: none
    # Composer
    - name: Run composer install
      run: composer install -n --prefer-dist
    # PHP Unit
    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        # configuration: /tests/phpunit.xml
        memory_limit: 256M
