name: Update Version Workflow

on:
  release:
    types: [published]

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Run custom script to update versions
      run: php ./scripts/update-versions.php "${{ github.event.release.tag_name }}"
