name: Update Version Workflow

on:
  release:
    types: [published]

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main  # Ensure that we are checking out the main branch

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  # Adjust as needed

    - name: Run custom script to update versions
      run: php ./.github/workflows/scripts/update-versions.php "${{ github.event.release.tag_name }}"

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Commit and push changes
      run: |
        git add composer.json package.json
        git commit -m "Update version numbers to ${{ github.event.release.tag_name }}"
        git push
