name: Publishing

on:
  release:
    types: [published]

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install jq
      run: sudo apt-get install -y jq
    - name: Run custom script to update versions
      run: ./scripts/update-versions.sh "${{ github.event.release.tag_name }}"
