name: Testing
on: [push]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        with:
          version: 11.0.9
          php_version: 8.3
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
  front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Front Tests
        run: npm test