name: Testing
on: [push]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        with:
          php_version: 8.3
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          args: --coverage-text